export const skillTech = [
	"HTML5 🌐",
	"CSS3 🎨",
	"JavaScript 📜",
	"React ⚛️",
	"Next.js 🚀",
	"Node.js 🟩",
	"TypeScript ⌨️",
	"Tailwind CSS 🌪️",
	"PostgreSQL 🗃️",
	"MySQL 🗄️",
	"React Native 📱",
	"Vue.js 🌿",
	"Nest.js 🐦",
	"Adonis.js 🎸",
	"Git 🧑‍💻",
	"Python 🐍",
	"Docker 🐋",
	"Styled Components 🎨",
	"Express.js 🚀",
];
